services:
  - type: web
    name: saim-dairy-farm
    env: node
    buildCommand: npm install && node init-db.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000